### ISSUE TITLE
training time?

### ISSUE THREAD

**Issue by wenqingchu** [taokong/RON#12]
Thanks for your impressive work. In my workstation with Titan X, it need about 3 second for each iteration. And the training time is about 100 hours (3*120000 second). Is it normal?

**Comment by wnzhyee** [comment]
Try reduce the batchsize to 10 in ./train_voc_reduced.sh and ./train_voc.sh

**Comment by wenqingchu** [comment]
@wnzhyee Have you tried that? Will it still achieve the same accuracy?
