### ISSUE TITLE
How to use 384 or other size for testing?

### ISSUE THREAD

**Issue by yushanshan05** [taokong/RON#13]
When I use test320cudnn.prototxt, all is right. 
But When I modify the input_shape to 384 in  test320cudnn.prototxt, there is error:
File "/opt/yushan/RON/tools/../lib/ron_layer/det_layer.py", line 72, in forward
    all_scores_det = bottom[1].data[:, 1:, :, :].reshape(self._ndim, self._numclasses - 1, self._num_anchors, self._height, self._width)
ValueError: cannot reshape array of size 5000 into shape (1,20,10,6,6)

I think the size of  det_cls_prob_7 is 5000 when size of input is 320. But  the size of  det_cls_prob_7 shuold be  7500 when size of input is 384.

This is the log of det_cls_prob_7 in testing.
 8690 net.cpp:434] det_cls_prob_7 <- det_cls_score_reshape_7
I1010 07:39:07.711601  8690 net.cpp:408] det_cls_prob_7 -> det_cls_prob_7
I1010 07:39:07.711802  8690 net.cpp:150] Setting up det_cls_prob_7
I1010 07:39:07.711809  8690 net.cpp:157] Top shape: 1 21 60 6 (7560)

It seems the size of  det_cls_prob_7 is all right. 
So I'm puzzled where the problem is. 
I only modify the input_shape. Is it right?How to use 384 or other size for testing?
Could you help me? Thanks!

**Comment by taokong** [comment]
change lib/fast_rcnn/config.py line 89 from 320 to 384 will work. Thanks

**Comment by yushanshan05** [comment]
Thank you very much!
