### ISSUE TITLE
Do RON have mxnet version?

### ISSUE THREAD

**Issue by xhzcyc** [taokong/RON#14]
Is there someone who did a mxnet version? 
Thanks

**Comment by HiKapok** [comment]
Hi, RON now have one un-official re-implementation using Tensorflow, now with a reduced vgg16 backbone 70.5% on VOC07 can be reached, and futher improvement is still going on. If you have interest please see [RON_Tensorflow](https://github.com/HiKapok/RON_Tensorflow)

**Comment by taokong** [comment]
@HiKapok 
Very nice job, and I will have a close look at this project!

**Comment by HiKapok** [comment]
@taokong thank you
