### ISSUE TITLE
Changing alpha and beta

### ISSUE THREAD

**Issue by shabnamghadar** [taokong/RON#16]
Hi,
thanks you so much for the code, can you tell me how can I change alpha and beta from equation(2)? This is to change the loss function
Thanks

**Comment by taokong** [comment]
Your can easily change them in the traing proto file (loss_weight)

**Comment by yushanshan05** [comment]
I have see that the loss_weight of rpn_loss_bbox, rpn_loss_cl and det_loss_cls is always 1. And alpha and beta in your paper is 0.3, Is it the same? Thanks!

**Comment by taokong** [comment]
Yes @yushanshan05
