### ISSUE TITLE
cuda/cudnn version

### ISSUE THREAD

**Issue by shabnamghadar** [taokong/RON#17]
Hi,
What is the cuda and cudnn version that you used? I tried compiling the code cuda 9/cudnn 8 and I am getting the following errors:

> src/caffe/net.cpp:8:18: fatal error: hdf5.h: No such file or directory
> compilation terminated.
> Makefile:575: recipe for target '.build_release/src/caffe/net.o' failed
> make: *** [.build_release/src/caffe/net.o] Error 1
> 

I have also tried with older versions (cuda 6.5 and cudnn 5) but I still can't get this to build

I would appreciate any advise
thanks

**Comment by taokong** [comment]
I think your problem may be the linux version (There are some difference in Ubuntu 14 and 16). Can you compile the official [caffe](https://github.com/BVLC/caffe)? My cuda 8.0 and cudnn 5/5.1
