### ISSUE TITLE
BaiduYun

### ISSUE THREAD

**Issue by shabnamghadar** [taokong/RON#18]
Hi ,
Thanks for the great code. I was wondering if you could host the VGG16_layers_fully_conv.caffemode for training (https://pan.baidu.com/s/1c2xm2U8#list/path=%2F) somewhere other than Baidu? It requires a  confirmation code with chinese area code to be able to download it. If this is the generic pre-trained VGG, can I download it from the modelzoo?

Thanks

**Comment by taokong** [comment]
Hi, @shabnamghadar 
You can find the pretrained models at [model zoo](https://github.com/BVLC/caffe/wiki/Model-Zoo). 

For original model, try the VGG16 model trained [VGG16](http://www.robots.ox.ac.uk/~vgg/research/very_deep/).

For fc-reduced model, try model [VGG16-reduced](https://gist.github.com/weiliu89/2ed6e13bfd5b57cf81d6) given by Wei Liu

I will move the models to GoogleDrive in recent days

**Comment by shabnamghadar** [comment]
Thanks very much

**Comment by taokong** [comment]
google drive model added @shabnamghadar
