### ISSUE TITLE
CUDNN error

### ISSUE THREAD

**Issue by c1874** [taokong/RON#19]
Thanks for your helpful work! When I am trying to run the code following the guide of yours,  I got the following issue:
F1119 15:00:44.842713 16912 cudnn.hpp:96] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM.

Could you please tell me how to deal with this? Thank you in advance.

**Comment by taokong** [comment]
Do you use the first device of your GPUs?
