### ISSUE TITLE
Multiple objects detection isn't so accurate

### ISSUE THREAD

**Issue by panovr** [taokong/RON#20]
Hi,
  I tried the RON VOC VGG-16 model on a test image.  Though there is a 'bird' class in the PASCAL VOC dataset, the detection isn't so accurate as it should be. 
  ![Original image](http://cs2.swfu.edu.cn/~zyl/RON/birds.jpg)
  ![The detection result](http://cs2.swfu.edu.cn/~zyl/RON/birds_det.jpg)
  @taokong May you also try RON on this image, thanks!

**Comment by franciszzj** [comment]
@panovr Perhaps the result is inaccurate, but it is correct for the criteria of evaluation. We still have a long way to go...

**Comment by panovr** [comment]
@Franciszzj It makes sense, thanks!

**Comment by twmht** [comment]
@panovr 

Did you solve the problem?

it looks like the same problem in #31

**Comment by foralliance** [comment]
@panovr 
![default](https://user-images.githubusercontent.com/23371826/40277036-ae713d30-5c4a-11e8-83bc-110d18aa1e0e.png)

**Comment by foralliance** [comment]
@panovr @twmht ![Uploading 图片.png…]()

**Comment by foralliance** [comment]
![default](https://user-images.githubusercontent.com/23371826/40277417-5639dc2e-5c51-11e8-8360-3dea59dc8b14.png)
