### ISSUE TITLE
Why this implementation is different from the paper?

### ISSUE THREAD

**Issue by HiKapok** [taokong/RON#25]
Hello, in your paper, fc7 use 2x2 convolution with stride 2, why this implementation replace fc6 with a large kernel convolution while fc7 just fully-conv? thx!

**Comment by taokong** [comment]
fc6-conv is the transformation from fully connected op to conv op. You can find the transformation in [Net Surgery](https://github.com/BVLC/caffe/blob/master/examples/net_surgery.ipynb)
