### ISSUE TITLE
What's the meaning of the number in rpn-data param "param_str"

### ISSUE THREAD

**Issue by qinyi20060410** [taokong/RON#28]
Hi,
recently，l'm reading your RON source code. I have a question about the file "traincudnn.prototxt". what's the meaning of param_str: "'stride_scale_border_batchsize': 64,7,32,256" in rpn-data_7 and this param_str in the other but the same position layer. I want to konw each meaning of the num in the param. 

Thanks.If disturbed, please forgive.

**Comment by taokong** [comment]
Just for usage of the rpn python layer
