### ISSUE TITLE
How can I use RON when the objects of my datasets are all small?

### ISSUE THREAD

**Issue by CQUCL** [taokong/RON#29]
First of all, thanks for your great work in object detection based on deep learning. I want to use RON framework to my own datasets, the objects of my datasets are all small. I only reserve rpn_lrn4 layer in order to detect small objects. I also change num_output to my own number of classes. My datasets only have two classes of objects , background and car. What's wrong with my changes? What else should I do?
     Looking foward your apply! Thanks!

**Comment by taokong** [comment]
You could try to enlarge the input size, or spit the images before imputing networks.
