### ISSUE TITLE
The demo result is not good

### ISSUE THREAD

**Issue by twmht** [taokong/RON#31]
@taokong 

I have tried the model (`RON320_VOC0712_VOC07.caffemodel`) you provided.

But the location of the bounding is not good.

For example, Here are the faster rcnn demo images.

![test](https://user-images.githubusercontent.com/1567200/38670294-f1bf9606-3e7a-11e8-8e12-9fdbdb99e4ac.jpg)

![test](https://user-images.githubusercontent.com/1567200/38670388-3749aef0-3e7b-11e8-9945-9d6931067967.jpg)

Any idea?

**Comment by taokong** [comment]
please check the code, and I think RON will detect such images. I will have a try.
